#!/bin/bash

RCLONE_REPO="ncw/rclone"
RELEASES=$(curl -qsL https://api.github.com/repos/${RCLONE_REPO}/tags | grep \"name\" | sed -ne 's/[^0-9]*\(\([0-9]\.\)\{0,4\}[0-9][^.]\).*/\1/p')
DOCKER_REPO="openbridge/ob_bulkstash"
IMG=$(basename $DOCKER_REPO)
for tag in ${RELEASES}; do
    echo "============== Building ${IMG}:$tag"
    docker build --build-arg RCLONE_VERSION=$tag -t ${DOCKER_REPO}:$tag .
done
latest=$(echo ${RELEASES}|cut -d" " -f1)
echo "============== Building ${IMG}:latest"
docker build --build-arg RCLONE_VERSION=$latest -t ${DOCKER_REPO}:latest .
